#!/usr/bin/env bash

# bundleops will build in the overloaded vector operators if set to 1
#
# installtools will install the node.js dependencies needed for building if set to 1

bundleops=1;installtools=0
#bundleops=0;installtools=0

mkdir -p tmp/src
mkdir -p tmp/es5
mkdir -p lib

if [ "$installtools" == 1 ]
 then
   npm install browserify
   npm install recast
   npm install estraverse
   npm install uglify-js -g
   npm install @babel/core @babel/cli @babel/preset-env
   browserify need-recast.js -o tmp/src/recast.js
   python3 patch-recast.py   
fi

cp vector-vectorify.js tmp/src/
cp vector-operators.js tmp/src/
if [ "$bundleops" != 1 ]
  then
      rm tmp/src/vector-operators.js
fi
npx babel tmp/src --presets=@babel/env --out-file tmp/es5/vectorify.js
uglifyjs --compress --mangle --beautify beautify=false,ascii_only=true -o lib/vectorify.js  tmp/es5/vectorify.js
# --preamble "/* vectorify.js by Morgan McGuire from https://casual-effects.com */"
# --mangle toplevel,reserved=['window','exports','Math','require','_recast','vectorify','_add','_mul','_div','_sub','dot','floor','round','trunc','ceil','pow','abs','sqrt','min','max','clamp','exp','maxComponent','minComponent','magnitude','direction','cross','cloneVector','copyVector']
# --mangle-props 1 --keep-fnames 
ls -al lib/vectorify.js


